# CMake generated Testfile for 
# Source directory: C:/Development/wireshark
# Build directory: C:/Development/wireshark
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_capture "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_capture")
  set_tests_properties(suite_capture PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_capture "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_capture")
  set_tests_properties(suite_capture PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_capture "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_capture")
  set_tests_properties(suite_capture PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_capture "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_capture")
  set_tests_properties(suite_capture PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_capture NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_clopts "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_clopts")
  set_tests_properties(suite_clopts PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_clopts "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_clopts")
  set_tests_properties(suite_clopts PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_clopts "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_clopts")
  set_tests_properties(suite_clopts PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_clopts "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_clopts")
  set_tests_properties(suite_clopts PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_clopts NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_decryption "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_decryption")
  set_tests_properties(suite_decryption PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_decryption "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_decryption")
  set_tests_properties(suite_decryption PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_decryption "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_decryption")
  set_tests_properties(suite_decryption PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_decryption "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_decryption")
  set_tests_properties(suite_decryption PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_decryption NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_bytes_ether "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_bytes_ether")
  set_tests_properties(suite_dfilter.group_bytes_ether PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_bytes_ether "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_bytes_ether")
  set_tests_properties(suite_dfilter.group_bytes_ether PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_bytes_ether "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_bytes_ether")
  set_tests_properties(suite_dfilter.group_bytes_ether PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_bytes_ether "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_bytes_ether")
  set_tests_properties(suite_dfilter.group_bytes_ether PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_bytes_ether NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_bytes_ipv6 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_bytes_ipv6")
  set_tests_properties(suite_dfilter.group_bytes_ipv6 PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_bytes_ipv6 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_bytes_ipv6")
  set_tests_properties(suite_dfilter.group_bytes_ipv6 PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_bytes_ipv6 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_bytes_ipv6")
  set_tests_properties(suite_dfilter.group_bytes_ipv6 PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_bytes_ipv6 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_bytes_ipv6")
  set_tests_properties(suite_dfilter.group_bytes_ipv6 PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_bytes_ipv6 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_bytes_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_bytes_type")
  set_tests_properties(suite_dfilter.group_bytes_type PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_bytes_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_bytes_type")
  set_tests_properties(suite_dfilter.group_bytes_type PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_bytes_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_bytes_type")
  set_tests_properties(suite_dfilter.group_bytes_type PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_bytes_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_bytes_type")
  set_tests_properties(suite_dfilter.group_bytes_type PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_bytes_type NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_double "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_double")
  set_tests_properties(suite_dfilter.group_double PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_double "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_double")
  set_tests_properties(suite_dfilter.group_double PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_double "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_double")
  set_tests_properties(suite_dfilter.group_double PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_double "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_double")
  set_tests_properties(suite_dfilter.group_double PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_double NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_dfunction_string "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_dfunction_string")
  set_tests_properties(suite_dfilter.group_dfunction_string PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_dfunction_string "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_dfunction_string")
  set_tests_properties(suite_dfilter.group_dfunction_string PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_dfunction_string "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_dfunction_string")
  set_tests_properties(suite_dfilter.group_dfunction_string PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_dfunction_string "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_dfunction_string")
  set_tests_properties(suite_dfilter.group_dfunction_string PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_dfunction_string NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_integer "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_integer")
  set_tests_properties(suite_dfilter.group_integer PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_integer "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_integer")
  set_tests_properties(suite_dfilter.group_integer PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_integer "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_integer")
  set_tests_properties(suite_dfilter.group_integer PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_integer "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_integer")
  set_tests_properties(suite_dfilter.group_integer PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_integer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_integer_1byte "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_integer_1byte")
  set_tests_properties(suite_dfilter.group_integer_1byte PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_integer_1byte "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_integer_1byte")
  set_tests_properties(suite_dfilter.group_integer_1byte PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_integer_1byte "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_integer_1byte")
  set_tests_properties(suite_dfilter.group_integer_1byte PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_integer_1byte "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_integer_1byte")
  set_tests_properties(suite_dfilter.group_integer_1byte PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_integer_1byte NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_ipv4 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_ipv4")
  set_tests_properties(suite_dfilter.group_ipv4 PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_ipv4 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_ipv4")
  set_tests_properties(suite_dfilter.group_ipv4 PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_ipv4 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_ipv4")
  set_tests_properties(suite_dfilter.group_ipv4 PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_ipv4 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_ipv4")
  set_tests_properties(suite_dfilter.group_ipv4 PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_ipv4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_membership "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_membership")
  set_tests_properties(suite_dfilter.group_membership PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_membership "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_membership")
  set_tests_properties(suite_dfilter.group_membership PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_membership "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_membership")
  set_tests_properties(suite_dfilter.group_membership PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_membership "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_membership")
  set_tests_properties(suite_dfilter.group_membership PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_membership NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_range_method "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_range_method")
  set_tests_properties(suite_dfilter.group_range_method PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_range_method "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_range_method")
  set_tests_properties(suite_dfilter.group_range_method PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_range_method "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_range_method")
  set_tests_properties(suite_dfilter.group_range_method PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_range_method "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_range_method")
  set_tests_properties(suite_dfilter.group_range_method PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_range_method NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_scanner "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_scanner")
  set_tests_properties(suite_dfilter.group_scanner PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_scanner "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_scanner")
  set_tests_properties(suite_dfilter.group_scanner PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_scanner "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_scanner")
  set_tests_properties(suite_dfilter.group_scanner PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_scanner "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_scanner")
  set_tests_properties(suite_dfilter.group_scanner PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_scanner NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_string_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_string_type")
  set_tests_properties(suite_dfilter.group_string_type PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_string_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_string_type")
  set_tests_properties(suite_dfilter.group_string_type PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_string_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_string_type")
  set_tests_properties(suite_dfilter.group_string_type PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_string_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_string_type")
  set_tests_properties(suite_dfilter.group_string_type PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_string_type NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_stringz "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_stringz")
  set_tests_properties(suite_dfilter.group_stringz PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_stringz "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_stringz")
  set_tests_properties(suite_dfilter.group_stringz PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_stringz "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_stringz")
  set_tests_properties(suite_dfilter.group_stringz PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_stringz "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_stringz")
  set_tests_properties(suite_dfilter.group_stringz PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_stringz NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_time_relative "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_time_relative")
  set_tests_properties(suite_dfilter.group_time_relative PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_time_relative "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_time_relative")
  set_tests_properties(suite_dfilter.group_time_relative PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_time_relative "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_time_relative")
  set_tests_properties(suite_dfilter.group_time_relative PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_time_relative "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_time_relative")
  set_tests_properties(suite_dfilter.group_time_relative PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_time_relative NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_time_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_time_type")
  set_tests_properties(suite_dfilter.group_time_type PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_time_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_time_type")
  set_tests_properties(suite_dfilter.group_time_type PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_time_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_time_type")
  set_tests_properties(suite_dfilter.group_time_type PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_time_type "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_time_type")
  set_tests_properties(suite_dfilter.group_time_type PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_time_type NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_tvb "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_tvb")
  set_tests_properties(suite_dfilter.group_tvb PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_tvb "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_tvb")
  set_tests_properties(suite_dfilter.group_tvb PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_tvb "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_tvb")
  set_tests_properties(suite_dfilter.group_tvb PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_tvb "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_tvb")
  set_tests_properties(suite_dfilter.group_tvb PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_tvb NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dfilter.group_uint64 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dfilter.group_uint64")
  set_tests_properties(suite_dfilter.group_uint64 PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dfilter.group_uint64 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dfilter.group_uint64")
  set_tests_properties(suite_dfilter.group_uint64 PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dfilter.group_uint64 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dfilter.group_uint64")
  set_tests_properties(suite_dfilter.group_uint64 PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dfilter.group_uint64 "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dfilter.group_uint64")
  set_tests_properties(suite_dfilter.group_uint64 PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dfilter.group_uint64 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dissection "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dissection")
  set_tests_properties(suite_dissection PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dissection "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dissection")
  set_tests_properties(suite_dissection PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dissection "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dissection")
  set_tests_properties(suite_dissection PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dissection "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dissection")
  set_tests_properties(suite_dissection PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dissection NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_dissectors.group_asterix "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_dissectors.group_asterix")
  set_tests_properties(suite_dissectors.group_asterix PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_dissectors.group_asterix "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_dissectors.group_asterix")
  set_tests_properties(suite_dissectors.group_asterix PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_dissectors.group_asterix "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_dissectors.group_asterix")
  set_tests_properties(suite_dissectors.group_asterix PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_dissectors.group_asterix "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_dissectors.group_asterix")
  set_tests_properties(suite_dissectors.group_asterix PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_dissectors.group_asterix NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_fileformats "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_fileformats")
  set_tests_properties(suite_fileformats PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_fileformats "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_fileformats")
  set_tests_properties(suite_fileformats PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_fileformats "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_fileformats")
  set_tests_properties(suite_fileformats PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_fileformats "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_fileformats")
  set_tests_properties(suite_fileformats PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_fileformats NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_follow "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_follow")
  set_tests_properties(suite_follow PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_follow "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_follow")
  set_tests_properties(suite_follow PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_follow "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_follow")
  set_tests_properties(suite_follow PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_follow "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_follow")
  set_tests_properties(suite_follow PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_follow NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_io "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_io")
  set_tests_properties(suite_io PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_io "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_io")
  set_tests_properties(suite_io PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_io "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_io")
  set_tests_properties(suite_io PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_io "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_io")
  set_tests_properties(suite_io PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_io NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_mergecap "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_mergecap")
  set_tests_properties(suite_mergecap PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_mergecap "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_mergecap")
  set_tests_properties(suite_mergecap PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_mergecap "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_mergecap")
  set_tests_properties(suite_mergecap PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_mergecap "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_mergecap")
  set_tests_properties(suite_mergecap PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_mergecap NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_nameres "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_nameres")
  set_tests_properties(suite_nameres PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_nameres "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_nameres")
  set_tests_properties(suite_nameres PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_nameres "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_nameres")
  set_tests_properties(suite_nameres PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_nameres "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_nameres")
  set_tests_properties(suite_nameres PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_nameres NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_outputformats "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_outputformats")
  set_tests_properties(suite_outputformats PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_outputformats "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_outputformats")
  set_tests_properties(suite_outputformats PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_outputformats "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_outputformats")
  set_tests_properties(suite_outputformats PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_outputformats "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_outputformats")
  set_tests_properties(suite_outputformats PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_outputformats NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_text2pcap "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_text2pcap")
  set_tests_properties(suite_text2pcap PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_text2pcap "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_text2pcap")
  set_tests_properties(suite_text2pcap PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_text2pcap "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_text2pcap")
  set_tests_properties(suite_text2pcap PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_text2pcap "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_text2pcap")
  set_tests_properties(suite_text2pcap PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_text2pcap NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_sharkd "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_sharkd")
  set_tests_properties(suite_sharkd PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_sharkd "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_sharkd")
  set_tests_properties(suite_sharkd PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_sharkd "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_sharkd")
  set_tests_properties(suite_sharkd PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_sharkd "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_sharkd")
  set_tests_properties(suite_sharkd PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_sharkd NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_unittests "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_unittests")
  set_tests_properties(suite_unittests PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_unittests "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_unittests")
  set_tests_properties(suite_unittests PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_unittests "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_unittests")
  set_tests_properties(suite_unittests PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_unittests "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_unittests")
  set_tests_properties(suite_unittests PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_unittests NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(suite_wslua "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Debug" "suite_wslua")
  set_tests_properties(suite_wslua PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(suite_wslua "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/Release" "suite_wslua")
  set_tests_properties(suite_wslua PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(suite_wslua "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/MinSizeRel" "suite_wslua")
  set_tests_properties(suite_wslua PROPERTIES  TIMEOUT "600")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(suite_wslua "C:/Program Files/CMake/bin/cmake.exe" "-E" "env" "PYTHONIOENCODING=UTF-8" "C:/Python37/python.exe" "C:/Development/wireshark/test/test.py" "--verbose" "--program-path" "./run/RelWithDebInfo" "suite_wslua")
  set_tests_properties(suite_wslua PROPERTIES  TIMEOUT "600")
else()
  add_test(suite_wslua NOT_AVAILABLE)
endif()
subdirs("zlib")
subdirs("capchild")
subdirs("caputils")
subdirs("codecs")
subdirs("doc")
subdirs("docbook")
subdirs("epan")
subdirs("extcap")
subdirs("randpkt_core")
subdirs("tools/lemon")
subdirs("ui")
subdirs("wiretap")
subdirs("writecap")
subdirs("wsutil")
subdirs("ui/qt")
subdirs("plugins/epan/ethercat")
subdirs("plugins/epan/gryphon")
subdirs("plugins/epan/irda")
subdirs("plugins/epan/mate")
subdirs("plugins/epan/opcua")
subdirs("plugins/epan/profinet")
subdirs("plugins/epan/stats_tree")
subdirs("plugins/epan/transum")
subdirs("plugins/epan/unistim")
subdirs("plugins/epan/wimax")
subdirs("plugins/epan/wimaxasncp")
subdirs("plugins/epan/wimaxmacphy")
subdirs("plugins/wiretap/usbdump")
subdirs("plugins/codecs/l16_mono")
