/* DO NOT EDIT
	This file was automatically generated by Pidl
	from bkrp.idl and bkrp.cnf.

	Pidl is a perl based IDL compiler for DCE/RPC idl files.
	It is maintained by the Samba team, not the Wireshark team.
	Instructions on how to download and install Pidl can be
	found at https://wiki.wireshark.org/Pidl
*/


#include "config.h"
#include <glib.h>
#include <string.h>
#include <epan/packet.h>

#include "packet-dcerpc.h"
#include "packet-dcerpc-nt.h"
#include "packet-windows-common.h"
#include "packet-dcerpc-bkrp.h"
void proto_register_dcerpc_backupkey(void);
void proto_reg_handoff_dcerpc_backupkey(void);

/* Ett declarations */
static gint ett_dcerpc_backupkey = -1;


/* Header field declarations */
static gint hf_backupkey_backupkey_BackuprKey_cbDataIn = -1;
static gint hf_backupkey_backupkey_BackuprKey_dwParam = -1;
static gint hf_backupkey_backupkey_BackuprKey_pDataIn = -1;
static gint hf_backupkey_backupkey_BackuprKey_pcbDataOut = -1;
static gint hf_backupkey_backupkey_BackuprKey_pguidActionAgent = -1;
static gint hf_backupkey_backupkey_BackuprKey_ppDataOut = -1;
static gint hf_backupkey_opnum = -1;
static gint hf_backupkey_status = -1;

static gint proto_dcerpc_backupkey = -1;
/* Version information */


static e_guid_t uuid_dcerpc_backupkey = {
	0x3dde7c30, 0x165d, 0x11d1,
	{ 0xab, 0x8f, 0x00, 0x80, 0x5f, 0x14, 0xdb, 0x40 }
};
static guint16 ver_dcerpc_backupkey = 1;

static int backupkey_dissect_element_BackuprKey_pguidActionAgent(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_pguidActionAgent_(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_pDataIn(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_pDataIn_(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_pDataIn__(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_cbDataIn(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_ppDataOut(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_ppDataOut_(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_ppDataOut__(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_ppDataOut___(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_pcbDataOut(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_pcbDataOut_(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);
static int backupkey_dissect_element_BackuprKey_dwParam(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_);

static int
backupkey_dissect_element_BackuprKey_pguidActionAgent(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = dissect_ndr_toplevel_pointer(tvb, offset, pinfo, tree, di, drep, backupkey_dissect_element_BackuprKey_pguidActionAgent_, NDR_POINTER_REF, "Pointer to PguidActionAgent (GUID)",hf_backupkey_backupkey_BackuprKey_pguidActionAgent);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_pguidActionAgent_(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = dissect_ndr_uuid_t(tvb, offset, pinfo, tree, di, drep, hf_backupkey_backupkey_BackuprKey_pguidActionAgent, NULL);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_pDataIn(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = dissect_ndr_toplevel_pointer(tvb, offset, pinfo, tree, di, drep, backupkey_dissect_element_BackuprKey_pDataIn_, NDR_POINTER_REF, "Pointer to PDataIn (uint8)",hf_backupkey_backupkey_BackuprKey_pDataIn);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_pDataIn_(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = dissect_ndr_ucarray(tvb, offset, pinfo, tree, di, drep, backupkey_dissect_element_BackuprKey_pDataIn__);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_pDataIn__(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = PIDL_dissect_uint8(tvb, offset, pinfo, tree, di, drep, hf_backupkey_backupkey_BackuprKey_pDataIn, 0);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_cbDataIn(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = PIDL_dissect_uint32(tvb, offset, pinfo, tree, di, drep, hf_backupkey_backupkey_BackuprKey_cbDataIn, 0);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_ppDataOut(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = dissect_ndr_toplevel_pointer(tvb, offset, pinfo, tree, di, drep, backupkey_dissect_element_BackuprKey_ppDataOut_, NDR_POINTER_REF, "Pointer to PpDataOut (uint8)",hf_backupkey_backupkey_BackuprKey_ppDataOut);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_ppDataOut_(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = dissect_ndr_embedded_pointer(tvb, offset, pinfo, tree, di, drep, backupkey_dissect_element_BackuprKey_ppDataOut__, NDR_POINTER_UNIQUE, "Pointer to PpDataOut (uint8)",hf_backupkey_backupkey_BackuprKey_ppDataOut);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_ppDataOut__(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = dissect_ndr_ucarray(tvb, offset, pinfo, tree, di, drep, backupkey_dissect_element_BackuprKey_ppDataOut___);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_ppDataOut___(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = PIDL_dissect_uint8(tvb, offset, pinfo, tree, di, drep, hf_backupkey_backupkey_BackuprKey_ppDataOut, 0);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_pcbDataOut(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = dissect_ndr_toplevel_pointer(tvb, offset, pinfo, tree, di, drep, backupkey_dissect_element_BackuprKey_pcbDataOut_, NDR_POINTER_REF, "Pointer to PcbDataOut (uint32)",hf_backupkey_backupkey_BackuprKey_pcbDataOut);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_pcbDataOut_(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = PIDL_dissect_uint32(tvb, offset, pinfo, tree, di, drep, hf_backupkey_backupkey_BackuprKey_pcbDataOut, 0);

	return offset;
}

static int
backupkey_dissect_element_BackuprKey_dwParam(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	offset = PIDL_dissect_uint32(tvb, offset, pinfo, tree, di, drep, hf_backupkey_backupkey_BackuprKey_dwParam, 0);

	return offset;
}

/* IDL: NTSTATUS backupkey_BackuprKey( */
/* IDL: [in] [ref] GUID *pguidActionAgent, */
/* IDL: [in] [ref] [size_is(cbDataIn)] uint8 *pDataIn, */
/* IDL: [in] uint32 cbDataIn, */
/* IDL: [out] [ref] [size_is(,*pcbDataOut)] uint8 **ppDataOut, */
/* IDL: [out] [ref] uint32 *pcbDataOut, */
/* IDL: [in] uint32 dwParam */
/* IDL: ); */

static int
backupkey_dissect_BackuprKey_response(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	guint32 status;

	di->dcerpc_procedure_name="BackuprKey";
	offset = backupkey_dissect_element_BackuprKey_ppDataOut(tvb, offset, pinfo, tree, di, drep);
	offset = dissect_deferred_pointers(pinfo, tvb, offset, di, drep);

	offset = backupkey_dissect_element_BackuprKey_pcbDataOut(tvb, offset, pinfo, tree, di, drep);
	offset = dissect_deferred_pointers(pinfo, tvb, offset, di, drep);

	offset = dissect_ntstatus(tvb, offset, pinfo, tree, di, drep, hf_backupkey_status, &status);

	if (status != 0)
		col_append_fstr(pinfo->cinfo, COL_INFO, ", Error: %s", val_to_str(status, NT_errors, "Unknown NT status 0x%08x"));

	return offset;
}

static int
backupkey_dissect_BackuprKey_request(tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, dcerpc_info* di _U_, guint8 *drep _U_)
{
	di->dcerpc_procedure_name="BackuprKey";
	offset = backupkey_dissect_element_BackuprKey_pguidActionAgent(tvb, offset, pinfo, tree, di, drep);
	offset = dissect_deferred_pointers(pinfo, tvb, offset, di, drep);
	offset = backupkey_dissect_element_BackuprKey_pDataIn(tvb, offset, pinfo, tree, di, drep);
	offset = dissect_deferred_pointers(pinfo, tvb, offset, di, drep);
	offset = backupkey_dissect_element_BackuprKey_cbDataIn(tvb, offset, pinfo, tree, di, drep);
	offset = dissect_deferred_pointers(pinfo, tvb, offset, di, drep);
	offset = backupkey_dissect_element_BackuprKey_dwParam(tvb, offset, pinfo, tree, di, drep);
	offset = dissect_deferred_pointers(pinfo, tvb, offset, di, drep);
	return offset;
}


static dcerpc_sub_dissector backupkey_dissectors[] = {
	{ 0, "BackuprKey",
	   backupkey_dissect_BackuprKey_request, backupkey_dissect_BackuprKey_response},
	{ 0, NULL, NULL, NULL }
};

void proto_register_dcerpc_backupkey(void)
{
	static hf_register_info hf[] = {
	{ &hf_backupkey_backupkey_BackuprKey_cbDataIn,
	  { "CbDataIn", "backupkey.backupkey_BackuprKey.cbDataIn", FT_UINT32, BASE_DEC, NULL, 0, NULL, HFILL }},
	{ &hf_backupkey_backupkey_BackuprKey_dwParam,
	  { "DwParam", "backupkey.backupkey_BackuprKey.dwParam", FT_UINT32, BASE_DEC, NULL, 0, NULL, HFILL }},
	{ &hf_backupkey_backupkey_BackuprKey_pDataIn,
	  { "PDataIn", "backupkey.backupkey_BackuprKey.pDataIn", FT_UINT8, BASE_DEC, NULL, 0, NULL, HFILL }},
	{ &hf_backupkey_backupkey_BackuprKey_pcbDataOut,
	  { "PcbDataOut", "backupkey.backupkey_BackuprKey.pcbDataOut", FT_UINT32, BASE_DEC, NULL, 0, NULL, HFILL }},
	{ &hf_backupkey_backupkey_BackuprKey_pguidActionAgent,
	  { "PguidActionAgent", "backupkey.backupkey_BackuprKey.pguidActionAgent", FT_GUID, BASE_NONE, NULL, 0, NULL, HFILL }},
	{ &hf_backupkey_backupkey_BackuprKey_ppDataOut,
	  { "PpDataOut", "backupkey.backupkey_BackuprKey.ppDataOut", FT_UINT8, BASE_DEC, NULL, 0, NULL, HFILL }},
	{ &hf_backupkey_opnum,
	  { "Operation", "backupkey.opnum", FT_UINT16, BASE_DEC, NULL, 0, NULL, HFILL }},
	{ &hf_backupkey_status,
	  { "NT Error", "backupkey.status", FT_UINT32, BASE_HEX, VALS(NT_errors), 0, NULL, HFILL }},
	};


	static gint *ett[] = {
		&ett_dcerpc_backupkey,
	};

	proto_dcerpc_backupkey = proto_register_protocol("BACKUPKEY (pidl)", "BACKUPKEY", "backupkey");
	proto_register_field_array(proto_dcerpc_backupkey, hf, array_length (hf));
	proto_register_subtree_array(ett, array_length(ett));
}

void proto_reg_handoff_dcerpc_backupkey(void)
{
	dcerpc_init_uuid(proto_dcerpc_backupkey, ett_dcerpc_backupkey,
		&uuid_dcerpc_backupkey, ver_dcerpc_backupkey,
		backupkey_dissectors, hf_backupkey_opnum);
}
